#!/bin/bash

RAWS=raws/*.NEF
mkdir orphaned_raws
for raw in $RAWS
do
    echo -n "Checking $raw - "
    rawb=$(basename $raw)
    jpg="${rawb%%.*}.JPG"
    if [ ! -f $jpg ];
    then
	echo "$jpg not found! Moving $rawb"
	mv $raw orphaned_raws
    else
	echo "$jpg found."
    fi
done
du -h orphaned_raws
