#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Pass raw extension as a argument."    
    exit 1
fi

RAWS=raws/*.$1
mkdir orphaned_raws
for raw in $RAWS
do
    echo -n "Checking $raw - "
    rawb=$(basename $raw)
    jpg="${rawb%%.*}.JPG"
    if [ ! -f $jpg ];
    then
	echo "$jpg not found! Moving $rawb"
	mv $raw orphaned_raws
    else
	echo "$jpg found."
    fi
done
du -h orphaned_raws
