#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Pass raw extension as a argument."    
    exit 1
fi

RAWS=raws/*.$1
for raw in $RAWS
do
    echo -n "Checking $raw - "
    rawb=$(basename $raw)
    jpg="${rawb%%.*}.JPG"
    if [ ! -f $jpg ];
    then
	echo "$jpg not found! Removing $rawb"
	rm $raw
    else
	echo "$jpg found."
    fi
done
