#!/bin/bash
mkdir resized
mogrify -verbose -path resized -resize 2464x2464\> -unsharp 2x0.5+0.7+0 -quality 90 *.jpg
mogrify -verbose -path resized -resize 2464x2464\> -unsharp 2x0.5+0.7+0 -quality 90 *.JPG
echo DONE!
